# Generated by Django 4.1 on 2023-02-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('star_point', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.book_user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.book_user')),
            ],
        ),
    ]
