# Generated by Django 4.1.7 on 2023-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('liked', models.PositiveIntegerField()),
            ],
        ),
    ]
