# Generated by Django 4.1 on 2023-02-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('liked', models.PositiveIntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comments_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
