# Generated by Django 4.1.7 on 2023-02-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
