# Generated by Django 4.1 on 2023-02-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='book_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
