# Generated by Django 4.1.6 on 2023-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=10, unique=True)),
                ('user_nickname', models.CharField(default='', max_length=10, unique=True)),
                ('user_login_id', models.CharField(default='', max_length=10, unique=True)),
                ('user_pw', models.CharField(default='', max_length=10)),
            ],
        ),
    ]