# Generated by Django 4.1.6 on 2023-02-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_user',
            name='user_name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='book_user',
            name='user_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='book_user',
            name='user_pw',
            field=models.CharField(default='', max_length=10),
        ),
    ]
